--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HyperEnte-PHP/CustomJoinMessage
build-by-default: true
branches:
- master
projects:
  JoinMessage:
    icon: "JoinMessageLOGO.png"
    path: JoinMessage/
...
